### ISSUE TITLE
Creating Schema results in error

### ISSUE THREAD

**Issue by marshalleq** [lalinsky/mbdata#5]
echo 'CREATE SCHEMA musicbrainz;' | mbslave psql -S

Results in:

Traceback (most recent call last):
  File "/usr/local/bin/mbslave", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/mbdata/replication.py", line 603, in main
    args.func(config, args)
  File "/usr/local/lib/python2.7/dist-packages/mbdata/replication.py", line 560, in mbslave_psql_main
    process = subprocess.Popen(command, env=environ)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
TypeError: coercing to Unicode: need string or buffer, int found

Apologies if this is me, however I had no trouble completing these pieces when installing mbslave rather than mbdata, so after much config stalking I'm assuming it's something in the instructions or in the configuration of the new code.

**Comment by marshalleq** [comment]
I note previously it was piping through mbslave-psql and now there is no -.

I assume that's intentional, either doesn't work anyway.

**Comment by lalinsky** [comment]
This is a bug fixed in https://github.com/lalinsky/mbdata/commit/8187f970aec6f1d57c741830565b26d9ad729810
